### ISSUE TITLE
Getting 403 Forbidden response

### ISSUE THREAD

**Issue by daminisinha** [Mrtenz/gatsby-plugin-aws-elasticsearch#7]
Hi, when I am trying to perform query with Jenkins user to AWS ElasticSearch I am getting forbidden in response as it fails to create an index.

While running in headless CI/CD mode, the accessKeyId, secretKey etc don't seem to work with the plugin (inside the config options), however, the same creds work with writing in a lambda function using vanilla javascript. 

The documentation says that the 'index' attribute in the config is mandatory and if the index doesn't exist, then it would be created. However, with the gatsby-plugin and working credentials, it fails to create a new index and I get a 403 forbidden error. The elasticsearch doesn't show any error logs as well in AWS console. 

```
error gatsby-plugin-aws-elasticsearch: Failed to synchronise with Elasticsearch: Failed to create index
  Error: Failed to create index
```
Thanks

**Comment by Mrtenz** [comment]
Can you please provide your plugin configuration?

**Comment by daminisinha** [comment]
I think managed to establish the connection by providing the session token which was missing from Options,thanks

**Comment by Mrtenz** [comment]
Great. I will close this issue then, feel free to open a new issue if you're running into other problems.
